/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function console_log(a: number, b: number): void;
export function __wbg_vector2d_free(a: number): void;
export function vector2d_new(a: number, b: number): number;
export function __wbg_particle_free(a: number): void;
export function __wbg_get_particle_position(a: number): number;
export function __wbg_set_particle_position(a: number, b: number): void;
export function __wbg_get_particle_velocity(a: number): number;
export function __wbg_set_particle_velocity(a: number, b: number): void;
export function __wbg_get_particle_mass(a: number): number;
export function __wbg_set_particle_mass(a: number, b: number): void;
export function particle_new(a: number, b: number, c: number): number;
export function __wbg_fluidsimulator_free(a: number): void;
export function __wbg_get_fluidsimulator_width(a: number): number;
export function __wbg_set_fluidsimulator_width(a: number, b: number): void;
export function __wbg_get_fluidsimulator_height(a: number): number;
export function __wbg_set_fluidsimulator_height(a: number, b: number): void;
export function __wbg_get_fluidsimulator_time_step(a: number): number;
export function __wbg_set_fluidsimulator_time_step(a: number, b: number): void;
export function __wbg_get_fluidsimulator_time(a: number): number;
export function __wbg_set_fluidsimulator_time(a: number, b: number): void;
export function __wbg_get_fluidsimulator_viscosity(a: number): number;
export function __wbg_set_fluidsimulator_viscosity(a: number, b: number): void;
export function __wbg_get_fluidsimulator_density(a: number, b: number): void;
export function __wbg_set_fluidsimulator_density(a: number, b: number, c: number): void;
export function __wbg_get_fluidsimulator_velocity_x(a: number, b: number): void;
export function __wbg_set_fluidsimulator_velocity_x(a: number, b: number, c: number): void;
export function __wbg_get_fluidsimulator_velocity_y(a: number, b: number): void;
export function __wbg_set_fluidsimulator_velocity_y(a: number, b: number, c: number): void;
export function __wbg_get_fluidsimulator_pressure(a: number, b: number): void;
export function __wbg_set_fluidsimulator_pressure(a: number, b: number, c: number): void;
export function __wbg_get_fluidsimulator_temperature(a: number, b: number): void;
export function __wbg_set_fluidsimulator_temperature(a: number, b: number, c: number): void;
export function __wbg_get_fluidsimulator_gravity(a: number): number;
export function __wbg_set_fluidsimulator_gravity(a: number, b: number): void;
export function __wbg_get_fluidsimulator_particle(a: number): number;
export function __wbg_set_fluidsimulator_particle(a: number, b: number): void;
export function __wbg_get_fluidsimulator_rendering_mode(a: number): number;
export function __wbg_set_fluidsimulator_rendering_mode(a: number, b: number): void;
export function fluidsimulator_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): number;
export function fluidsimulator_add_force(a: number, b: number, c: number, d: number, e: number): void;
export function fluidsimulator_step(a: number): void;
export function fluidsimulator_set_rendering_mode(a: number, b: number, c: number): void;
export function fluidsimulator_get_data(a: number): number;
export function fluidsimulator_get_statistics(a: number, b: number): void;
export function __wbg_get_vector2d_y(a: number): number;
export function __wbg_get_vector2d_x(a: number): number;
export function __wbg_set_vector2d_x(a: number, b: number): void;
export function __wbg_set_vector2d_y(a: number, b: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
